# Generated by Django 2.0 on 2018-03-30 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readnums',
            name='read_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
