# Generated by Django 2.0 on 2018-04-25 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_readnums_read_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readnums',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
