# Generated by Django 2.0 on 2018-04-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_auto_20180413_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_supuser',
            field=models.BooleanField(default=False),
        ),
    ]
