# Generated by Django 2.0 on 2018-05-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0006_checkcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkcode',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
