# Generated by Django 2.0 on 2018-03-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180329_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read_nums',
            field=models.IntegerField(default=0),
        ),
    ]
