# Generated by Django 2.0 on 2018-04-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('blog', '0010_auto_20180403_1855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
