# Generated by Django 2.0 on 2018-04-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180403_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='1321131987@qq.com', max_length=254),
        ),
    ]
