# Generated by Django 2.0 on 2018-04-25 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_type',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_type',
            field=models.ManyToManyField(to='blog.BlogType'),
        ),
    ]
